### ISSUE TITLE
Hex Color Messenger

### ISSUE THREAD

**Issue by hhenrichsen** [ShatteredSuite/ShatteredCore#9]
Pull in Adventure, and apply it to the messenger so that we support all of the fancy things that come along with the formatting.

https://github.com/KyoriPowered/adventure

Probably, just the MiniMessage portion of it.

**Comment by peculiaruc** [comment]
please has this be taken, I am interested in it

**Comment by hhenrichsen** [comment]
It's not taken; I'll assign it to you.

**Comment by peculiaruc** [comment]
Oh! Sorry can you please re-assign this task.  Never worked on an API
before.
